### ISSUE TITLE
Changing the favicon color when in break mode

### ISSUE THREAD

**Issue by MoutaiA** [FabioDevCode/Pomodoro-App#2]
# Description

For the sake of more visibility, it'll be cool to have the favicon in green when we're in break mode.

Eventually having in a more neutral color when everything is in pause, like gray, or yellow.

Basically we would have 3 colors:
- Red: during a work session
- Green: while we're in a pause mode
- Yellow/Gray (or whatever): when the clock is not running

**Comment by FabioDevCode** [comment]
I fix it.

Now,  when a cycle of pomodoro is over, you can see a grey favicon with "Finish" text.
